services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5858:5858
    depends_on:
      - db
  db:
    image:  postgres 
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
    

